packaging_format = 2

id = "beehive"
name = "Beehive"
description.en = "Flexible event/agent & automation system"
description.fr = "Système flexible d'événement et d'automatisation"

version = "0.4.0~ynh3"

maintainers = []

[upstream]
license = "AGPL-3.0-or-later"
demo = "https://github.com/muesli/beehive/wiki/Available-Hives"
code = "https://github.com/muesli/beehive"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        in_subdir = false
        arm64.url = "https://github.com/muesli/beehive/releases/download/v0.4.0/beehive_0.4.0_Linux_arm64.tar.gz"
        arm64.sha256 = "d8ad07d68eadaa7b8a52df9c0b35b64902f6b9435096ccfad57ff7e20d262cd9"
        amd64.url = "https://github.com/muesli/beehive/releases/download/v0.4.0/beehive_0.4.0_Linux_x86_64.tar.gz"
        amd64.sha256 = "f1959bc2f7c19d4ec8eaabc7b78492836afcc3bcd75d034854e66607efa9efab"
        armhf.url = "https://github.com/muesli/beehive/releases/download/v0.4.0/beehive_0.4.0_Linux_armv6.tar.gz"
        armhf.sha256 = "c1fa8f5a1935ee12f09a2bd9579281d64552897c597534361aba90ed992676fb"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "^beehive_.*_Linux_arm64.tar.gz$"
        autoupdate.asset.amd64 = "^beehive_.*_Linux_x86_64.tar.gz$"
        autoupdate.asset.armhf = "^beehive_.*_Linux_armv6.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
